import Head from "next/head";
import styles from "../styles/Home.module.css";
import Portal from "./components/portal";
import { ThemeProvider } from "@material-ui/styles";
import configuracaoDoTema from "./tema";
import SiteNamoros from "./components/siteNamoros";
import React from "react";
import styled from "styled-components";
import { Switch, Route } from "react-router";

export default function Home() {
  const estaEmAlgumaPaginaDoPortal = () => {
    const palavrasDoLink = location.pathname;
    return palavrasDoLink.some((palavra) => palavra === "portal");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="stylesheet" href="https://use.typekit.net/miq3ufo.css" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
          rel="stylesheet"
        />
        <html lang="pt-br" />
      </Head>

      <ThemeProvider theme={configuracaoDoTema}>
        <Main>
          <Switch>
            <Route path={estaEmAlgumaPaginaDoPortal()}>
              <Portal />
            </Route>
            <Route path={!estaEmAlgumaPaginaDoPortal()}>
              <SiteNamoros />
            </Route>
          </Switch>
        </Main>
      </ThemeProvider>
    </div>
  );
}

const Main = styled.div`
  display: flex;
  justify-content: center;
`;
